// import { useEffect } from 'react';
// import { useRouter } from 'next/router';
// import { useDispatch, useSelector } from 'react-redux';
// import { fetchReportById } from '../../redux/actions/reportActions';

// const ReportDetails = () => {
//   const router = useRouter();
//   const { id } = router.query; // Get the report ID from the URL
//   const dispatch = useDispatch();
//   const { report, loading, error } = useSelector((state) => state.reports);

//   useEffect(() => {
//     if (id) {
//       dispatch(fetchReportById(id)); // Fetch report details when the page loads
//     }
//   }, [dispatch, id]);

//   if (loading) return <div>Loading...</div>;
//   if (error) return <div>Error: {error}</div>;

//   return (
//     <div className="p-8">
//       <h1 className="text-2xl font-bold mb-4">Report Details</h1>
//       {report && (
//         <div className="p-4 bg-white shadow-md rounded-lg">
//           <h2 className="text-xl font-semibold">Type: {report.type}</h2>
//           <p>Generated By: {report.generatedBy.name}</p>
//           <p>Generated On: {new Date(report.generatedAt).toLocaleString()}</p>
//           <h3 className="text-lg font-semibold mt-4">Data:</h3>
//           <pre className="bg-gray-100 p-4 rounded-lg">
//             {JSON.stringify(report.data, null, 2)}
//           </pre>
//         </div>
//       )}
//     </div>
//   );
// };

// export default ReportDetails;

import React from 'react'

const ReportDetails = () => {
  return (
    <div>Hello world</div>
  )
}

export default ReportDetails
